"""Core event and candidate models for VoiceReach.

These models define the protocol between all system components:
- IALEvent: Unified input events from gaze, finger, blink, keyboard
- Candidate/CandidateSet: LLM-generated response candidates
- WebSocket message types for backend <-> patient UI communication
"""

from __future__ import annotations

import time
from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


class EventType(str, Enum):
    """Unified IAL event types."""
    SELECT = "SELECT"
    CONFIRM = "CONFIRM"
    CANCEL = "CANCEL"
    EMERGENCY = "EMERGENCY"
    SCROLL = "SCROLL"


class InputSource(str, Enum):
    """Input source identifiers."""
    GAZE = "gaze"
    FINGER = "finger"
    BLINK = "blink"
    KEYBOARD = "keyboard"


class ScrollDirection(str, Enum):
    """Scroll directions for SCROLL events."""
    UP = "up"
    DOWN = "down"
    LEFT = "left"
    RIGHT = "right"


class IALEvent(BaseModel):
    """Input Abstraction Layer unified event.

    All input sources (gaze, finger tap, blink, keyboard) produce
    IALEvent instances through their respective adapters.
    """
    event_type: EventType
    source: InputSource
    target_id: int | None = None
    confidence: float = Field(ge=0.0, le=1.0, default=1.0)
    timestamp_ms: int = Field(default_factory=lambda: int(time.time() * 1000))
    scroll_direction: ScrollDirection | None = None


class IntentAxis(str, Enum):
    """7-axis intent framework for diverse candidate generation."""
    EMOTIONAL_RESPONSE = "emotional_response"
    QUESTION = "question"
    SELF_REFERENCE = "self_reference"
    OTHER_REFERENCE = "other_reference"
    ACTION_REQUEST = "action_request"
    HUMOR = "humor"
    TOPIC_CHANGE = "topic_change"


class GenerationStage(int, Enum):
    """LLM generation stage in the three-tier hybrid pipeline."""
    LOCAL_FAST = 1      # Qwen3-0.6B (~150ms)
    LOCAL_QUALITY = 2   # Qwen3-1.7B (~350ms)
    CLOUD = 3           # Gemini 2.5 Flash (~800ms)


class Candidate(BaseModel):
    """A single response candidate generated by the LLM pipeline."""
    text: str
    intent_axis: IntentAxis
    confidence: float = Field(ge=0.0, le=1.0)
    generation_stage: GenerationStage
    latency_ms: int = Field(ge=0)


class CandidateSet(BaseModel):
    """A set of candidates from a single generation stage."""
    candidates: list[Candidate] = Field(max_length=4)
    stage: GenerationStage
    request_id: str
    timestamp_ms: int = Field(default_factory=lambda: int(time.time() * 1000))
    is_final: bool = False


# --- WebSocket Protocol Messages ---

class GazeUpdate(BaseModel):
    """Client -> Server: Gaze zone update from eye tracking."""
    type: Literal["gaze_update"] = "gaze_update"
    zone_id: int = Field(ge=0)
    confidence: float = Field(ge=0.0, le=1.0)
    timestamp_ms: int


class InputEvent(BaseModel):
    """Client -> Server: IAL event from input layer."""
    type: Literal["input_event"] = "input_event"
    event: IALEvent


class CandidateSelected(BaseModel):
    """Client -> Server: User selected a candidate."""
    type: Literal["candidate_selected"] = "candidate_selected"
    request_id: str
    candidate_index: int = Field(ge=0, le=3)


class CandidateUpdate(BaseModel):
    """Server -> Client: New/updated candidates from LLM pipeline."""
    type: Literal["candidate_update"] = "candidate_update"
    request_id: str
    candidate_set: CandidateSet
    is_final: bool = False


class TTSReady(BaseModel):
    """Server -> Client: TTS audio ready for playback."""
    type: Literal["tts_ready"] = "tts_ready"
    audio_url: str
    text: str
    duration_ms: int = 0


class EmergencyAck(BaseModel):
    """Server -> Client: Emergency acknowledged."""
    type: Literal["emergency_ack"] = "emergency_ack"
    notified_caregivers: list[str] = Field(default_factory=list)


# Union type for WebSocket message routing
ClientMessage = GazeUpdate | InputEvent | CandidateSelected
ServerMessage = CandidateUpdate | TTSReady | EmergencyAck
